In [1]:
import pandas as pd

list_data=["Vivek","Vivan","Vantika","Mamta","Vaibhav"]
students_data = [
    {
        "Name": "John",
        "Gender": "M",
        "DOB": "5/4/88",
        "Maths": 55,
        "Physics": 45,
        "Chemistry": 56,
        "English": 87,
        "Biology": 21,
        "Economics": 52,
        "History": 89,
        "Civics": 65
    },
    {
        "Name": "Suresh",
        "Gender": "M",
        "DOB": "4/5/87",
        "Maths": 75,
        "Physics": 55,
        "Chemistry": None,
        "English": 64,
        "Biology": 90,
        "Economics": 61,
        "History": 58,
        "Civics": 2
    },
    {
        "Name": "Ramesh",
        "Gender": "M",
        "DOB": "25/5/1989",
        "Maths": 25,
        "Physics": 54,
        "Chemistry": 89,
        "English": 76,
        "Biology": 95,
        "Economics": 87,
        "History": 56,
        "Civics": 74
    },
    {
        "Name": "Jessica",
        "Gender": "F",
        "DOB": "12/8/90",
        "Maths": 78,
        "Physics": 55,
        "Chemistry": 86,
        "English": 63,
        "Biology": 54,
        "Economics": 89,
        "History": 75,
        "Civics": 45
    },
    {
        "Name": "Jennifer",
        "Gender": "F",
        "DOB": "2/9/89",
        "Maths": 58,
        "Physics": 96,
        "Chemistry": 78,
        "English": 46,
        "Biology": 96,
        "Economics": 77,
        "History": 83,
        "Civics": 53
    }
]
import pandas as pd
import numpy as np
df = pd.DataFrame(students_data)
print(df.iloc[:,3:])
avg_df=df.iloc[:,3:].fillna(0).apply(np.average,axis=1)
df['Average']=avg_df
print("Getting average of the subject studentwise:\n")
df

print("Shape:\n",df.shape)
print("Info:\n",df.info())
print("Indexs:\n",df.index)
print("Columns:\n",df.columns)

np_result=df.to_numpy()
print("Numpy array shape:\n",np_result.shape)







#Basic operation on the dataframe loc and iloc
result= df.loc[(df['Chemistry']>70) & (df['Maths']>75)]
print("Result after and condition\n")
result
print(result.shape)


result= df.loc[0:]
print("Result after and condition\n")
result


## set index and axis
result=df.set_index(df['Name'])
print("After setting the index as the name column:\n")
result
print("John math number:\n",result.loc['John','Maths'])


## set axis 
result=df.set_axis(["name_"+str(x) for x in df.index],axis='index')
print("after set axis:\n")
result





#filters

result=df.filter(items=["Name","Average"])
print("Filtering using two columns:\n")
result
print("Numpy Shape:\n",result.shape)

result=df.filter(items=df.columns[3::])
print("Filtering using total number of columns:\n")
result
result=df.filter(like="Maths")
result

   Maths  Physics  Chemistry  English  Biology  Economics  History  Civics
0     55       45       56.0       87       21         52       89      65
1     75       55        NaN       64       90         61       58       2
2     25       54       89.0       76       95         87       56      74
3     78       55       86.0       63       54         89       75      45
4     58       96       78.0       46       96         77       83      53
Getting average of the subject studentwise:

Shape:
 (5, 12)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       5 non-null      object
 1   Gender     5 non-null      object
 2   DOB        5 non-null      object
 3   Maths      5 non-null      int64
 4   Physics    5 non-null      int64
 5   Chemistry  4 non-null      float64
 6   English    5 non-null      int64
 7   Biology    5 non-null      int64
 8   Economics  5 non-null      int64
 9   History    5 non-null      int64
 10  Civics     5 non-null      int64
 11  Average    5 non-null      float64
dtypes: float64(2), int64(7), object(3)
memory usage: 612.0+ bytes
Info:
 None
Indexs:
 RangeIndex(start=0, stop=5, step=1)
Columns:
 Index(['Name', 'Gender', 'DOB', 'Maths', 'Physics', 'Chemistry', 'English',
       'Biology', 'Economics', 'History', 'Civics', 'Average'],
      dtype='object')
Numpy array shape:
 (5, 12)
Result after and condition

(1, 12)
Result after and condition

After setting the index as the name column:

John math number:
 55
after set axis:

Filtering using two columns:

Numpy Shape:
 (5, 2)
Filtering using total number of columns:

   Maths
0     55
1     75
2     25
3     78
4     58

In [2]:
__author__ = "Vivek"
__author_email__ = "vivekltp120@gmail.com"


## Find the average in the pandas dataframe

import pandas as pd
import numpy as np
import os


students_data = [
    {
        "Name": "John",
        "Gender": "M",
        "DOB": "5/4/88",
        "Maths": 55,
        "Physics": 45,
        "Chemistry": 56,
        "English": 87,
        "Biology": 21,
        "Economics": 52,
        "History": 89,
        "Civics": 65
    },
    {
        "Name": "Suresh",
        "Gender": "M",
        "DOB": "4/5/87",
        "Maths": 75,
        "Physics": 55,
        "Chemistry": None,
        "English": 64,
        "Biology": 90,
        "Economics": 61,
        "History": 58,
        "Civics": 2
    },
    {
        "Name": "Ramesh",
        "Gender": "M",
        "DOB": "25/5/1989",
        "Maths": 25,
        "Physics": 54,
        "Chemistry": 89,
        "English": 76,
        "Biology": 95,
        "Economics": 87,
        "History": 56,
        "Civics": 74
    },
    {
        "Name": "Jessica",
        "Gender": "F",
        "DOB": "12/8/90",
        "Maths": 78,
        "Physics": 55,
        "Chemistry": 86,
        "English": 63,
        "Biology": 54,
        "Economics": 89,
        "History": 75,
        "Civics": 45
    },
    {
        "Name": "Jennifer",
        "Gender": "F",
        "DOB": "2/9/89",
        "Maths": 58,
        "Physics": 96,
        "Chemistry": 78,
        "English": 46,
        "Biology": 96,
        "Economics": 77,
        "History": 83,
        "Civics": 53
    }
]


def average_student():
    global avg_df
    # print(df.iloc[:,3:7])
    # avg_df=df.fillna(0).loc[:,["Maths","Physics","Chemistry","English"]].apply(np.average,axis=1)
    # axis=1 along row means --->
    # Average for all subject student wise
    avg_df = df.fillna(0).iloc[:, 3:].apply(np.average, axis=1)
    print(avg_df)
    # df["Average"] = avg_df
    # print("Average:\n\n ", df)


def drop_column():
    # Drop the column
    new_df = pd.concat([df, avg_df], axis=1)
    print("After dropping the column:\n\n", new_df.drop(["Gender", "Name"], axis=1))


def rename_column():
    # replace column levels
    df.rename(columns={"Maths": "Mathematics"}, inplace=True)
    print("After rename:\n\n", df)


def setaxis():
    # set the column or row(index) level
    # to set the axis for the column and row(index)
    df_index = df.set_axis(["a", "b", "c", "d", "e"], axis='index')
    print("After set index:\n\n", df_index)
    # set the column as index
    print("After set column as index:\n\n", df.set_index("Name"))


def write_data(df, file_name="out.xlsx", sheet_name="sheet_1"):
    # write df dinto the csv file
    with pd.ExcelWriter(file_name) as ewriter:
        df.to_excel(ewriter, sheet_name=sheet_name)


def read_data(file):
    # csv file
    if os.path.exists(file) and os.path.splitext(file) == ".csv":
        reader = pd.read_csv(file)
        return reader

    #xlsx file reader
    if os.path.exists(file) and os.path.splitext(file)[1] in [".xls",".xlsx"] :
               reader=pd.read_excel(file)
               new_columns=reader.iloc[18]
               new_df=reader.iloc[19:,].rename(columns=new_columns)
               new_df=new_df.reset_index()
               new_df=new_df.drop(axis=0,labels=[len(new_df)-1, len(new_df)-2])
               new_df=new_df.drop(labels=['index'],axis=1)
               new_df=change_column_content(new_df,'Description')
               #sum of debit
               write_data(new_df,file_name="sbi.xlsx",sheet_name="stmt_sbi")

def change_column_content(df,column):
    temp=df[column]
    temp=temp.apply(lambda x:x.split('/')[-1])
    df[column]=temp
    return df

def pandas_filter(df,columns):
    pass



    
    
    
if __name__ == "__main__":
    df = pd.DataFrame(students_data)
    xl_file="/media/vivek/Data/Vivek/Interview_Prep/CompetitiveCoding/expenses/sbi_Oct_20_Aug_21.xlsx"
    average_student()
    drop_column()
    rename_column()
    setaxis()
    # write_data(df)
    read_data(xl_file)

0    58.750
1    50.625
2    69.500
3    68.125
4    73.375
dtype: float64
After dropping the column:

          DOB  Maths  Physics  Chemistry  English  Biology  Economics  History  \
0     5/4/88     55       45       56.0       87       21         52       89
1     4/5/87     75       55        NaN       64       90         61       58
2  25/5/1989     25       54       89.0       76       95         87       56
3    12/8/90     78       55       86.0       63       54         89       75
4     2/9/89     58       96       78.0       46       96         77       83

   Civics       0
0      65  58.750
1       2  50.625
2      74  69.500
3      45  68.125
4      53  73.375
After rename:

        Name Gender        DOB  Mathematics  Physics  Chemistry  English  \
0      John      M     5/4/88           55       45       56.0       87
1    Suresh      M     4/5/87           75       55        NaN       64
2    Ramesh      M  25/5/1989           25       54       89.0       76
3   Jessica      F    12/8/90           78       55       86.0       63
4  Jennifer      F     2/9/89           58       96       78.0       46

   Biology  Economics  History  Civics
0       21         52       89      65
1       90         61       58       2
2       95         87       56      74
3       54         89       75      45
4       96         77       83      53
After set index:

        Name Gender        DOB  Mathematics  Physics  Chemistry  English  \
a      John      M     5/4/88           55       45       56.0       87
b    Suresh      M     4/5/87           75       55        NaN       64
c    Ramesh      M  25/5/1989           25       54       89.0       76
d   Jessica      F    12/8/90           78       55       86.0       63
e  Jennifer      F     2/9/89           58       96       78.0       46

   Biology  Economics  History  Civics
a       21         52       89      65
b       90         61       58       2
c       95         87       56      74
d       54         89       75      45
e       96         77       83      53
After set column as index:

          Gender        DOB  Mathematics  Physics  Chemistry  English  Biology  \
Name
John          M     5/4/88           55       45       56.0       87       21
Suresh        M     4/5/87           75       55        NaN       64       90
Ramesh        M  25/5/1989           25       54       89.0       76       95
Jessica       F    12/8/90           78       55       86.0       63       54
Jennifer      F     2/9/89           58       96       78.0       46       96

          Economics  History  Civics
Name
John             52       89      65
Suresh           61       58       2
Ramesh           87       56      74
Jessica          89       75      45
Jennifer         77       83      53

In [3]:
#Important operations for pandas dataframe
import pandas as pd
import numpy as np
df=pd.read_csv("Data/nba.csv")
#sorting in pandas dataframe
df.sort_values(["Team","Age","Salary"],axis=0,inplace=True)
df.describe()
df

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
318,Dennis Schroder,Atlanta Hawks,17.0,PG,22.0,6-1,172.0,NaN,1763400.0
317,Lamar Patterson,Atlanta Hawks,13.0,SG,24.0,6-5,225.0,Pittsburgh,525093.0
316,Mike Muscala,Atlanta Hawks,31.0,PF,24.0,6-11,240.0,Bucknell,947276.0
322,Walter Tavares,Atlanta Hawks,22.0,C,24.0,7-3,260.0,NaN,1000000.0
310,Tim Hardaway Jr.,Atlanta Hawks,10.0,SG,24.0,6-6,205.0,Michigan,1304520.0
...,...,...,...,...,...,...,...,...,...
373,Marcin Gortat,Washington Wizards,13.0,C,32.0,6-11,240.0,NaN,11217391.0
368,Alan Anderson,Washington Wizards,6.0,SG,33.0,6-6,220.0,Michigan State,4000000.0
375,Nene Hilario,Washington Wizards,42.0,C,33.0,6-11,250.0,NaN,13000000.0
372,Drew Gooden,Washington Wizards,90.0,PF,34.0,6-10,250.0,Kansas,3300000.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
#grouping in dataframe
group_team=df.groupby(["Team"])
group_team.describe()
#operation in pandas
for team, group in group_team:
    print(team)
    # print(group.describe())

('Atlanta Hawks',)
('Boston Celtics',)
('Brooklyn Nets',)
('Charlotte Hornets',)
('Chicago Bulls',)
('Cleveland Cavaliers',)
('Dallas Mavericks',)
('Denver Nuggets',)
('Detroit Pistons',)
('Golden State Warriors',)
('Houston Rockets',)
('Indiana Pacers',)
('Los Angeles Clippers',)
('Los Angeles Lakers',)
('Memphis Grizzlies',)
('Miami Heat',)
('Milwaukee Bucks',)
('Minnesota Timberwolves',)
('New Orleans Pelicans',)
('New York Knicks',)
('Oklahoma City Thunder',)
('Orlando Magic',)
('Philadelphia 76ers',)
('Phoenix Suns',)
('Portland Trail Blazers',)
('Sacramento Kings',)
('San Antonio Spurs',)
('Toronto Raptors',)
('Utah Jazz',)
('Washington Wizards',)

In [5]:
#correlation
print(df.loc[:,["Age","Weight","Salary","Number"]].corr(method="pearson"))
print(df.loc[:,['Age',"Weight"]].corr(method="kendall"))
print(df.loc[:,['Age',"Weight"]].corr(method="spearman"))

             Age    Weight    Salary    Number
Age     1.000000  0.087183  0.213459  0.028724
Weight  0.087183  1.000000  0.138321  0.206921
Salary  0.213459  0.138321  1.000000 -0.112386
Number  0.028724  0.206921 -0.112386  1.000000
            Age   Weight
Age     1.00000  0.06613
Weight  0.06613  1.00000
             Age    Weight
Age     1.000000  0.096163
Weight  0.096163  1.000000